name: Project-Stats CI

on:
  schedule:
    - cron: "0 */4 * * *" # every 4 hours
  repository_dispatch:
    types: [sync-project-data]

env:
  THIRD_PARTY_GIT_AUTHOR_EMAIL: opensource+bot@newrelic.com
  THIRD_PARTY_GIT_AUTHOR_NAME: nr-opensource-bot

jobs:
  job-sync-project-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.0
        with:
          ref: main
          fetch-depth: 0
          token: ${{ secrets.OPENSOURCE_BOT_TOKEN }}

      - name: Sync Data
        uses: ./.github/actions/sync-data
        with:
          github-token: ${{ secrets.NEWRELIC_BOT_TOKEN }} # must have push access to repos for stats queries to work
          project-stats: true

      - name: Commit data files
        run: |
          git config --local user.email "${{ env.THIRD_PARTY_GIT_AUTHOR_EMAIL }}"
          git config --local user.name "${{ env.THIRD_PARTY_GIT_AUTHOR_NAME }}"

          # main could have been modified since we checked out, so pull before pushing
          git pull --ff-only origin main

          echo "Updated project data files -- committing"
          git add src/data
          git commit -m "chore(stats): updated project stats files"

          # Push to main here rather than using github-push-action
          echo "Pushing to main"
          git push origin main

  job-checkout-and-build:
    runs-on: ubuntu-latest
    needs: job-sync-project-data
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2.3.0

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Cache node_modules
        id: cache-node
        uses: actions/cache@v2
        env:
          cache-name: node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ env.cache-name }}-

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Gatsby Build
        run: |
          if [ '${{ github.ref }}' = 'refs/heads/develop' ]; then
            yarn run build:staging
          elif [ '${{ github.ref }}' = 'refs/heads/main' ]; then
            yarn run build:production
          else
            echo "::error::Running on unsupported branch. Exiting."
            exit 1
          fi
